#include <ctype.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "support.h"

#define MAXLINE       512
#define MAXVERNAMELEN 64
#define DEFAULT_VERSION_FILE "_version.h"

uint8_t textOverride;
enum { CRLF = 1, LF }; // override options

string_t template     = { 0 };

char *defaultTemplate = "// Autogenerated version file\n"
                        "#define GIT_VERSION \"@V@\"\n";

static char *trim(char *s) {
    while (isspace(*s))
        s++;
    if (*s) {
        char *t = strchr(s, '\0') - 1;
        while (isspace(*t))
            *t-- = '\0';
    }
    return s;
}

enum { CONFIG, SKIP, TEMPLATE };

char *parseConfig(char const *cfgFileName) {
    char line[MAXLINE];
    char *versionFile = NULL;
    uint8_t state = CONFIG;
    FILE *fp      = fopen(cfgFileName, "rt");
    if (fp) {
        while (fgets(line, MAXLINE, fp)) {
            char *s = line;
            while (*s && isspace(*s))
                s++;
            if (state == CONFIG && *s == '[') {
                char *vFile = ++s;
                while (*s) {
                    if (*s == ']') {
                        *s      = '\0';
                        char *t = strchr(vFile, '|');
                        if (t) {
                            *t = '\0';
                            t  = trim(t + 1);
                            if (stricmp(t, "crlf") == 0)
                                textOverride = CRLF;
                            else if (stricmp(t, "lf") == 0)
                                textOverride = LF;
                        }
                        if (*(vFile = trim(vFile)))
                            versionFile = safeStrdup(vFile);
                        state = SKIP;
                    } else
                        s++;
                }
            } else if (*s || state == TEMPLATE) {
                appendString(&template, line);
                state = TEMPLATE;
            }
        }
        fclose(fp);
    } else if (stricmp(cfgFileName, "version.in") != 0)
        warn("Configuration file '%s' not found", cfgFileName);

    if (template.pos == 0) {
        debugPrint("Using default template");
        appendString(&template, defaultTemplate);
    }
    appendBuffer(&template, "", 1);
    return versionFile ? versionFile : safeStrdup(DEFAULT_VERSION_FILE);
}

bool writeNewVersion(char const *versionFile, char const *version, char const *date) {
    FILE *fp = fopen(versionFile, textOverride ? "wb" : "wt");
    if (!fp) {
        warn("Cannot create %s", versionFile);
        return false;
    }
    for (char *s = template.str; *s; s++) {
        if (*s == '@' && s[1] && s[2] == '@') {
            if (tolower(s[1]) == 'v') {
                fputs(version, fp);
                s += 2;
                continue;
            } else if (tolower(s[1]) == 'd') {
                fputs(date, fp);
                s += 2;
                continue;
            }
        }
        if (*s != '\r') {
            if (*s == '\n' && textOverride == CRLF)
                putc('\r', fp);
            putc(*s, fp);
        }
    }
    fclose(fp);
    return true;
}
