// Autogenerated default version file
#ifndef v1_18_9_3
#define v1_18_9_3
#define GIT_APPID       "td02img"
#define GIT_APPNAME     "td02img"
#define GIT_VERSION     "1.18.9x"
#define GIT_VERSION_RC  0,0,0,0
#define GIT_SHA1        "untracked"
#define GIT_BUILDTYPE   2 
#define GIT_CTIME       "2021-08-25 14:07:04"
#define GIT_YEAR        "2021"
#endif
